"""production hardening fields

Revision ID: 7e7d91aae581
Revises: b9f06eff171c
Create Date: 2026-07-02 12:15:37.754927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e7d91aae581'
down_revision: Union[str, None] = 'b9f06eff171c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.add_column('ride_requests', sa.Column('origin_latitude', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('origin_longitude', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('destination_latitude', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('destination_longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('origin_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('origin_longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('email_verification_token_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_token_hash')
    op.drop_column('users', 'email_verified')
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'origin_longitude')
    op.drop_column('trips', 'origin_latitude')
    op.drop_column('ride_requests', 'destination_longitude')
    op.drop_column('ride_requests', 'destination_latitude')
    op.drop_column('ride_requests', 'origin_longitude')
    op.drop_column('ride_requests', 'origin_latitude')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
