"""initial schema

Revision ID: b9f06eff171c
Revises: 
Create Date: 2026-07-02 12:07:05.079563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9f06eff171c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('rider', 'driver', 'admin', name='userrole'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='gender'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    op.create_table('ride_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('preferred_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('gender_preference', sa.Enum('none', 'same_gender', name='genderpreference'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'cancelled', 'completed', name='riderequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_ride_requests_preferred_time'), 'ride_requests', ['preferred_time'], unique=False)
    op.create_index(op.f('ix_ride_requests_request_id'), 'ride_requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_rider_id'), 'ride_requests', ['rider_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_status'), 'ride_requests', ['status'], unique=False)
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('posted', 'matched', 'ongoing', 'completed', 'cancelled', 'full', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trips_departure_time'), 'trips', ['departure_time'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_trip_id'), 'trips', ['trip_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicles_verification_status'), 'vehicles', ['verification_status'], unique=False)
    op.create_table('location_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_location_logs_log_id'), 'location_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_location_logs_timestamp'), 'location_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_location_logs_trip_id'), 'location_logs', ['trip_id'], unique=False)
    op.create_index(op.f('ix_location_logs_user_id'), 'location_logs', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('recommended', 'confirmed', 'rejected', 'cancelled', 'completed', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ride_requests.request_id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_matches_request_id'), 'matches', ['request_id'], unique=False)
    op.create_index(op.f('ix_matches_rider_id'), 'matches', ['rider_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_trip_id'), 'matches', ['trip_id'], unique=False)
    op.create_table('ratings_reports',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Enum('late', 'unsafe', 'rude', 'fake_account', 'payment_issue', 'other', name='reporttype'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_ratings_reports_from_user_id'), 'ratings_reports', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_ratings_reports_record_id'), 'ratings_reports', ['record_id'], unique=False)
    op.create_index(op.f('ix_ratings_reports_to_user_id'), 'ratings_reports', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_ratings_reports_trip_id'), 'ratings_reports', ['trip_id'], unique=False)
    op.create_table('sos_events',
    sa.Column('sos_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('new', 'reviewing', 'resolved', 'false_alarm', name='sosstatus'), nullable=False),
    sa.Column('triggered_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sos_id')
    )
    op.create_index(op.f('ix_sos_events_sos_id'), 'sos_events', ['sos_id'], unique=False)
    op.create_index(op.f('ix_sos_events_status'), 'sos_events', ['status'], unique=False)
    op.create_index(op.f('ix_sos_events_trip_id'), 'sos_events', ['trip_id'], unique=False)
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('simulated_ewallet', name='paymentmethod'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_match_id'), 'payments', ['match_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_match_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_trip_id'), table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_status'), table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_sos_id'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_ratings_reports_trip_id'), table_name='ratings_reports')
    op.drop_index(op.f('ix_ratings_reports_to_user_id'), table_name='ratings_reports')
    op.drop_index(op.f('ix_ratings_reports_record_id'), table_name='ratings_reports')
    op.drop_index(op.f('ix_ratings_reports_from_user_id'), table_name='ratings_reports')
    op.drop_table('ratings_reports')
    op.drop_index(op.f('ix_matches_trip_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_rider_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_request_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_location_logs_user_id'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_trip_id'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_timestamp'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_log_id'), table_name='location_logs')
    op.drop_table('location_logs')
    op.drop_index(op.f('ix_vehicles_verification_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_trips_trip_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_time'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_ride_requests_status'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_rider_id'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_request_id'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_preferred_time'), table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
